name: http_wrapper
version: 0.0.2

description: A simple dart:http wrapper using validator and parser
repository: https://github.com/nvkantonio/dart_http_wrapper
homepage: https://github.com/nvkantonio/dart_http_wrapper
issue_tracker: https://github.com/nvkantonio/dart_http_wrapper/issues

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
